[build]
  publish = "."
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/calculator/*"
  to = "/.netlify/functions/calculator/:splat"
  status = 200

[[redirects]]
  from = "/api/friends/*"
  to = "/.netlify/functions/friends/:splat"
  status = 200

[[redirects]]
  from = "/api/friends"
  to = "/.netlify/functions/friends"
  status = 200

[[redirects]]
  from = "/calculator/*"
  to = "/.netlify/functions/calculator/:splat"
  status = 200

[[redirects]]
  from = "/friends/*"
  to = "/.netlify/functions/friends/:splat"
  status = 200

[[redirects]]
  from = "/friends"
  to = "/.netlify/functions/friends"
  status = 200

[[redirects]]
  from = "/api/server1/*"
  to = "/.netlify/functions/servers/server1/:splat"
  status = 200

[[redirects]]
  from = "/api/server2/*"
  to = "/.netlify/functions/servers/server2/:splat"
  status = 200

[[redirects]]
  from = "/api/server3/*"
  to = "/.netlify/functions/servers/server3/:splat"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 8888
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
